name: Python application test with GitHub Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio
        pip install -r requirements.txt
    - name: Run Pylinter
      uses: programmingwithalex/pylinter@v1.4.3
      with:
        python-root: '.'
    - name: Run main.py
      run: |
        python main.py
